### ISSUE TITLE
Sane behaviour when not attached to a tty

### ISSUE THREAD

**Issue by athre0z** [athre0z/zzz#1]
When the application printing the progress bar is not attached to a terminal, we definitely shouldn't be flooding stdout at 60 refreshes per second. When the application is printing to e.g. a docker log, we'd cause an unreasonable amount of disk space usage. A separate formatter / printer should be used when a non-tty is detected, printing significantly less frequently.

**Comment by frereit** [comment]
Rust just [announced Rust 1.70.0](https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html) which includes the `IsTerminal` trait:

```rust
use std::io::{stdout, IsTerminal};

fn main() {
    let use_color = stdout().is_terminal();
    // if so, add color codes to program output...
}
```
This is relevant for this issue because it means this can be implemented without requiring any extra dependencies.

**Comment by athre0z** [comment]
Heh yes, I also thought of this issue when reading the changelog yesterday. It's nice to have that in the standard library. But let's wait for another month or so until more people have a compatible toolchain as their default before we implement this.

**Comment by frereit** [comment]
Would it perhaps make sense to completely disable `should_draw` by default on non-terminals?

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 38464a4..1c637e0 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -2,7 +2,7 @@
 
 use std::{
     fmt::{self, Write as _},
-    io::{self, stderr, Write as _},
+    io::{self, stderr, Write as _, IsTerminal},
     sync::atomic::{AtomicUsize, Ordering::Relaxed},
     sync::RwLock,
     time::{Duration, Instant},
@@ -57,7 +57,7 @@ impl Config {
             min_bar_width: 5,
             theme: &DefaultTheme,
             max_fps: 60.0,
-            should_draw: &|| true,
+            should_draw: &|| stderr().is_terminal(),
         }
     }
 }
```

**Comment by athre0z** [comment]
Yeah, that might be best indeed. Very few applications draw progress bars when printing  to non-tty. From the top of my head, the only one that comes to mind is curl, and it has always annoyed me that they do this. (might actually be non-default flag that turns this on for curl, but I frequently see it in dockerfiles)
